### ISSUE TITLE
Username is mandatory when adding name to a tenant but there is no name flag

### ISSUE THREAD

**Issue by Alevsk** [minio/m3#111]
When trying to add a new user to a tenant via cli username is mandatory but there is no flag to specify the name

`./m3 tenant user add --tenant company-inc --email user@acme.com --password user1234`

Error:

`User name is needed`

**Comment by cesnietor** [comment]
yes, we need to update the README to
`./m3 tenant user add --tenant company-inc --name somename --email user@acme.com --password user1234`

**Comment by Alevsk** [comment]
fixed on https://github.com/minio/m3/commit/7dd6cb89b41e66850093681988bb9fee0af574f7
