### ISSUE TITLE
Validate Tenant Short Name on creation

### ISSUE THREAD

**Issue by dvaldivia** [minio/m3#32]
We need to make sure the tenants being created have a valid short name as that's used as identifier and subdomain.

Add this validation as a function so it can be re-used in many places.

A valid tenant short name must:
- [ ] Is globally unique
- [ ] min 2 characters
- [ ] max 64 characters
- [ ] is only lowecase, numbers and dashes `[a-z0-9-]{2,64}`
- [ ] Not a reserved word: m3, kube-system, default, kube-public, kube-node-lease

**Comment by u5surf** [comment]
Hi, I’d like to fix this issue.
