### ISSUE TITLE
Apply changes to Deployments as a merge operation instead of Delete/Create

### ISSUE THREAD

**Issue by dvaldivia** [minio/m3#37]
Right now, when we are re-deploying a Tenant we are deleting the deployment for the Storage Group and then re-creating it (Delete->Create), this has a problem that we loose deployment metadata.

We should instead do `Get->Update` to preserve other metadata that the deployment may have.

**Comment by krisis** [comment]
https://github.com/minio/m3/pull/67 fixes this
