### ISSUE TITLE
Add securityContext for the pods as default

### ISSUE THREAD

**Issue by harshavardhana** [minio/m3#88]
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ to allow MinIO to run as non-root on these pods

**Comment by harshavardhana** [comment]
@dvaldivia ^^ this is an important requirement to run MinIO as non-root containers

**Comment by dvaldivia** [comment]
will look into this as soon as I can

**Comment by dvaldivia** [comment]
Can you look into this @Alevsk

**Comment by Alevsk** [comment]
I'll start taking a look at this
